// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyhJ_ihupcU-nrw9ovarhVjGLXHolPDe4',
    appId: '1:599453892493:web:505f03369a9eff1ce5c7c4',
    messagingSenderId: '599453892493',
    projectId: 'web-wrapper-delivery-driver',
    authDomain: 'web-wrapper-delivery-driver.firebaseapp.com',
    storageBucket: 'web-wrapper-delivery-driver.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2HPS14NWAR7H1iu2xEYdsZaTlYQmLU4k',
    appId: '1:599453892493:android:f2fcf5b80ed4ee77e5c7c4',
    messagingSenderId: '599453892493',
    projectId: 'web-wrapper-delivery-driver',
    storageBucket: 'web-wrapper-delivery-driver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoWr6rqNAM7wokReiIvD2S_b-oEhK-LCk',
    appId: '1:599453892493:ios:478b105fdfb749c5e5c7c4',
    messagingSenderId: '599453892493',
    projectId: 'web-wrapper-delivery-driver',
    storageBucket: 'web-wrapper-delivery-driver.firebasestorage.app',
    iosBundleId: 'com.fooddelivery.driverapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoWr6rqNAM7wokReiIvD2S_b-oEhK-LCk',
    appId: '1:599453892493:ios:478b105fdfb749c5e5c7c4',
    messagingSenderId: '599453892493',
    projectId: 'web-wrapper-delivery-driver',
    storageBucket: 'web-wrapper-delivery-driver.firebasestorage.app',
    iosBundleId: 'com.fooddelivery.driverapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyhJ_ihupcU-nrw9ovarhVjGLXHolPDe4',
    appId: '1:599453892493:web:37eb69bb9cf91628e5c7c4',
    messagingSenderId: '599453892493',
    projectId: 'web-wrapper-delivery-driver',
    authDomain: 'web-wrapper-delivery-driver.firebaseapp.com',
    storageBucket: 'web-wrapper-delivery-driver.firebasestorage.app',
  );

}
